/opt/stock-website/.logs/*.log /opt/stock-website/.logs/*.jsonl {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su stock-website stock-website
}
